version: "3.9"

services:
  docker:
    image: docker:dind
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: ""
    command: --storage-driver=overlay2
    expose:
      - 2375
      - 2376

  builder:
    image: mrmerseri/builder:1
    container_name: builder
    environment:
      DOCKER_HOST: tcp://docker:2375
      DOCKER_TLS_CERTDIR: ""
    command: docker ps -a