name: Docker Deploy

on:
  push:
    branches:
      - main

env:
  DOCKER_HUB: mrmerseri

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Identify changed files
        id: files
        uses: lots0logs/gh-action-get-changed-files@2.2.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine Dockerfile and Tag
        id: dockerfile
        run: |
          if echo "${{ steps.files.outputs.modified }}" | grep -q 'builder/'; then
            DOCKERFILE=$(echo "${{ steps.files.outputs.modified }}" | grep 'builder/' | head -n 1)
            TAG=$(basename $DOCKERFILE .dockerfile)
            FOLDER=$(basename $(dirname $DOCKERFILE))
            echo "::set-output name=dockerfile::$DOCKERFILE"
            echo "::set-output name=tag::${FOLDER}-${TAG}"
          elif echo "${{ steps.files.outputs.modified }}" | grep -q 'deploy-tools/'; then
            DOCKERFILE=$(echo "${{ steps.files.outputs.modified }}" | grep 'deploy-tools/' | head -n 1)
            TAG=$(basename $DOCKERFILE .dockerfile)
            FOLDER=$(basename $(dirname $DOCKERFILE))
            echo "::set-output name=dockerfile::$DOCKERFILE"
            echo "::set-output name=tag::${FOLDER}-${TAG}"
          else
            echo "No relevant changes detected"
            exit 78
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ${{ steps.dockerfile.outputs.dockerfile }}
          push: true
          tags: ${{ env.DOCKER_HUB }}/${{ steps.dockerfile.outputs.tag }}
